//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdisMart_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialSubasta
    {
        public int id { get; set; }
        public int subasta_id { get; set; }
        public int usuario_id { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Subasta Subasta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
