//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdisMart_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subasta
    {
        public Subasta()
        {
            this.HistorialSubasta = new HashSet<HistorialSubasta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_cierre { get; set; }
        public Nullable<decimal> monto_mas_alto { get; set; }
        public Nullable<int> ganador_id { get; set; }
        public Nullable<int> creador_id { get; set; }
        public string imagen_url { get; set; }
    
        public virtual ICollection<HistorialSubasta> HistorialSubasta { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
