//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdisMart_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.HistorialSubasta = new HashSet<HistorialSubasta>();
            this.Subasta = new HashSet<Subasta>();
            this.Subasta1 = new HashSet<Subasta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasena { get; set; }
    
        public virtual ICollection<HistorialSubasta> HistorialSubasta { get; set; }
        public virtual ICollection<Subasta> Subasta { get; set; }
        public virtual ICollection<Subasta> Subasta1 { get; set; }
    }
}
